In [1]:
import requests
import json
import pandas as pd

In [4]:
path = r'C:\Users\Magsihim_AI\Desktop\Project_Statbotics\full_table.csv'

df = pd.read_csv(path)

C:\Users\Magsihim_AI\AppData\Local\Temp\ipykernel_7616\1835638036.py:3: DtypeWarning: Columns (17,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,52,53,54,55,56,57,58,59,60,61,62,63,65,66,67,74,75,76,77,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,111,112,113,114,115,116,117,118,119,120,121,122,128,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,163,164,165,166,167,168,169,170,171,172,173,174,176,177,178,185,186,187,188,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,222,223,224,225,226,227,228,229,230,231,232,233,237,238) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

In [5]:
df.loc[~df['winning_alliance'].isin(['red', 'blue']), 'winning_alliance'] = 'tie'

In [6]:
df.drop(['blue_alliance', 'red_alliance'], axis = 1, inplace = True)

In [7]:
df['red_teams_lst'] = df['red_teams'].apply(lambda x: x.split(', '))
df['blue_teams_lst'] = df['blue_teams'].apply(lambda x: x.split(', '))

In [8]:
df['blue_Robot1'] = df['blue_teams_lst'].apply(lambda x: x[0] if len(x) > 0 else None)
df['blue_Robot2'] = df['blue_teams_lst'].apply(lambda x: x[1] if len(x) > 0 else None)
df['blue_Robot3'] = df['blue_teams_lst'].apply(lambda x: x[2] if len(x) > 0 else None)

In [9]:
df['red_Robot1'] = df['red_teams_lst'].apply(lambda x: x[0] if len(x) > 0 else None)
df['red_Robot2'] = df['red_teams_lst'].apply(lambda x: x[1] if len(x) > 0 else None)
df['red_Robot3'] = df['red_teams_lst'].apply(lambda x: x[2] if len(x) > 0 else None)

In [10]:
df.drop(['blue_teams_lst', 'red_teams_lst', 'blue_teams', 'red_teams'], axis = 1, inplace = True)

In [11]:
df.drop(['red_totalPoints', 'blue_totalPoints'], axis=1, inplace=True)

In [12]:
df

,actual_time,comp_level,event_key,key,match_number,post_result_time,predicted_time,set_number,time,videos,...,red_teleopReef_topRow_nodeK,red_teleopReef_topRow_nodeL,red_teleopReef_trough,red_wallAlgaeCount,blue_Robot1,blue_Robot2,blue_Robot3,red_Robot1,red_Robot2,red_Robot3
0,1.742056e+09,f,2025alhu,2025alhu_f1m1,1,1.742056e+09,1.742056e+09,1,1.742056e+09,"[{'key': 'NSWVoO4ZDEs', 'type': 'youtube'}]",...,False,True,0.0,0.0,frc2338,frc4020,frc10011,frc2783,frc4028,frc7111
1,1.742058e+09,f,2025alhu,2025alhu_f1m2,2,1.742058e+09,1.742058e+09,1,1.742057e+09,"[{'key': '1FpcfKgS3kw', 'type': 'youtube'}]",...,True,False,0.0,0.0,frc2338,frc4020,frc10011,frc2783,frc4028,frc7111
2,1.741960e+09,qm,2025alhu,2025alhu_qm1,1,1.741960e+09,1.741960e+09,1,1.741960e+09,"[{'key': 'mAbsfvQlhaw', 'type': 'youtube'}]",...,False,False,5.0,2.0,frc2973,frc6107,frc9410,frc5045,frc34,frc4020
3,1.741965e+09,qm,2025alhu,2025alhu_qm10,10,1.741965e+09,1.741965e+09,1,1.741965e+09,"[{'key': 'xrkAU-qZY-E', 'type': 'youtube'}]",...,True,True,1.0,0.0,frc3138,frc3843,frc4020,frc538,frc2338,frc2973
4,1.741965e+09,qm,2025alhu,2025alhu_qm11,11,1.741965e+09,1.741965e+09,1,1.741965e+09,"[{'key': 'ae-lJ4geVPg', 'type': 'youtube'}]",...,True,True,1.0,1.0,frc7428,frc8772,frc4028,frc6107,frc6517,frc48
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19619,1.752379e+09,sf,2025xxmel,2025xxmel_sf5m1,1,1.752379e+09,1.752379e+09,5,1.752378e+09,[],...,True,True,11.0,0.0,frc9146,frc9147,frc9995,frc7128,frc9189,frc5648
19620,1.752379e+09,sf,2025xxmel,2025xxmel_sf6m1,1,1.752379e+09,1.752379e+09,6,1.752379e+09,[],...,False,False,5.0,0.0,frc4729,frc9986,frc9991,frc9996,frc5876,frc10552
19621,1.752380e+09,sf,2025xxmel,2025xxmel_sf7m1,1,1.752380e+09,1.752380e+09,7,1.752380e+09,[],...,True,True,0.0,0.0,frc4774,frc4537,frc9994,frc6510,frc5584,frc9974
19622,1.752380e+09,sf,2025xxmel,2025xxmel_sf8m1,1,1.752380e+09,1.752380e+09,8,1.752381e+09,[],...,True,True,4.0,0.0,frc6996,frc9976,frc9993,frc6497,frc9992,frc10002
19623,1.752381e+09,sf,2025xxmel,2025xxmel_sf9m1,1,1.752381e+09,1.752381e+09,9,1.752381e+09,[],...,False,False,0.0,0.0,frc4729,frc9986,frc9991,frc4774,frc4537,frc9994

In [13]:
df[['blue_endGameRobot1', 'blue_endGameRobot2', 'blue_endGameRobot3', 'red_endGameRobot1', 'red_endGameRobot2', 'red_endGameRobot3']] = df[['blue_endGameRobot1', 'blue_endGameRobot2', 'blue_endGameRobot3', 'red_endGameRobot1', 'red_endGameRobot2', 'red_endGameRobot3']].fillna('Nothing')

In [14]:
df[['blue_endGameRobot1', 'blue_endGameRobot2', 'blue_endGameRobot3', 'red_endGameRobot1', 'red_endGameRobot2', 'red_endGameRobot3']]

,blue_endGameRobot1,blue_endGameRobot2,blue_endGameRobot3,red_endGameRobot1,red_endGameRobot2,red_endGameRobot3
0,Parked,DeepCage,Parked,Parked,Parked,Parked
1,Parked,DeepCage,Parked,DeepCage,DeepCage,Parked
2,Nothing,Parked,Nothing,Nothing,Parked,DeepCage
3,Parked,Parked,Parked,Parked,DeepCage,Parked
4,Parked,Parked,DeepCage,Parked,Parked,Parked
...,...,...,...,...,...,...
19619,DeepCage,Nothing,Parked,DeepCage,Parked,Parked
19620,Nothing,Nothing,Nothing,Parked,Parked,Nothing
19621,DeepCage,Parked,Parked,Parked,DeepCage,Parked
19622,Parked,Parked,Parked,Parked,Parked,Nothing
19623,Nothing,Parked,Parked,DeepCage,DeepCage,DeepCage

In [15]:
df['red_scorePenaltyFree'] = df['red_score'] - df['red_foulPoints']
df['blue_scorePenaltyFree'] = df['blue_score'] - df['blue_foulPoints']

In [16]:
df

,actual_time,comp_level,event_key,key,match_number,post_result_time,predicted_time,set_number,time,videos,...,red_teleopReef_trough,red_wallAlgaeCount,blue_Robot1,blue_Robot2,blue_Robot3,red_Robot1,red_Robot2,red_Robot3,red_scorePenaltyFree,blue_scorePenaltyFree
0,1.742056e+09,f,2025alhu,2025alhu_f1m1,1,1.742056e+09,1.742056e+09,1,1.742056e+09,"[{'key': 'NSWVoO4ZDEs', 'type': 'youtube'}]",...,0.0,0.0,frc2338,frc4020,frc10011,frc2783,frc4028,frc7111,124.0,143.0
1,1.742058e+09,f,2025alhu,2025alhu_f1m2,2,1.742058e+09,1.742058e+09,1,1.742057e+09,"[{'key': '1FpcfKgS3kw', 'type': 'youtube'}]",...,0.0,0.0,frc2338,frc4020,frc10011,frc2783,frc4028,frc7111,144.0,149.0
2,1.741960e+09,qm,2025alhu,2025alhu_qm1,1,1.741960e+09,1.741960e+09,1,1.741960e+09,"[{'key': 'mAbsfvQlhaw', 'type': 'youtube'}]",...,5.0,2.0,frc2973,frc6107,frc9410,frc5045,frc34,frc4020,129.0,37.0
3,1.741965e+09,qm,2025alhu,2025alhu_qm10,10,1.741965e+09,1.741965e+09,1,1.741965e+09,"[{'key': 'xrkAU-qZY-E', 'type': 'youtube'}]",...,1.0,0.0,frc3138,frc3843,frc4020,frc538,frc2338,frc2973,112.0,97.0
4,1.741965e+09,qm,2025alhu,2025alhu_qm11,11,1.741965e+09,1.741965e+09,1,1.741965e+09,"[{'key': 'ae-lJ4geVPg', 'type': 'youtube'}]",...,1.0,1.0,frc7428,frc8772,frc4028,frc6107,frc6517,frc48,61.0,124.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19619,1.752379e+09,sf,2025xxmel,2025xxmel_sf5m1,1,1.752379e+09,1.752379e+09,5,1.752378e+09,[],...,11.0,0.0,frc9146,frc9147,frc9995,frc7128,frc9189,frc5648,85.0,64.0
19620,1.752379e+09,sf,2025xxmel,2025xxmel_sf6m1,1,1.752379e+09,1.752379e+09,6,1.752379e+09,[],...,5.0,0.0,frc4729,frc9986,frc9991,frc9996,frc5876,frc10552,26.0,72.0
19621,1.752380e+09,sf,2025xxmel,2025xxmel_sf7m1,1,1.752380e+09,1.752380e+09,7,1.752380e+09,[],...,0.0,0.0,frc4774,frc4537,frc9994,frc6510,frc5584,frc9974,135.0,65.0
19622,1.752380e+09,sf,2025xxmel,2025xxmel_sf8m1,1,1.752380e+09,1.752380e+09,8,1.752381e+09,[],...,4.0,0.0,frc6996,frc9976,frc9993,frc6497,frc9992,frc10002,90.0,73.0
19623,1.752381e+09,sf,2025xxmel,2025xxmel_sf9m1,1,1.752381e+09,1.752381e+09,9,1.752381e+09,[],...,0.0,0.0,frc4729,frc9986,frc9991,frc4774,frc4537,frc9994,76.0,57.0

In [17]:
df

,actual_time,comp_level,event_key,key,match_number,post_result_time,predicted_time,set_number,time,videos,...,red_teleopReef_trough,red_wallAlgaeCount,blue_Robot1,blue_Robot2,blue_Robot3,red_Robot1,red_Robot2,red_Robot3,red_scorePenaltyFree,blue_scorePenaltyFree
0,1.742056e+09,f,2025alhu,2025alhu_f1m1,1,1.742056e+09,1.742056e+09,1,1.742056e+09,"[{'key': 'NSWVoO4ZDEs', 'type': 'youtube'}]",...,0.0,0.0,frc2338,frc4020,frc10011,frc2783,frc4028,frc7111,124.0,143.0
1,1.742058e+09,f,2025alhu,2025alhu_f1m2,2,1.742058e+09,1.742058e+09,1,1.742057e+09,"[{'key': '1FpcfKgS3kw', 'type': 'youtube'}]",...,0.0,0.0,frc2338,frc4020,frc10011,frc2783,frc4028,frc7111,144.0,149.0
2,1.741960e+09,qm,2025alhu,2025alhu_qm1,1,1.741960e+09,1.741960e+09,1,1.741960e+09,"[{'key': 'mAbsfvQlhaw', 'type': 'youtube'}]",...,5.0,2.0,frc2973,frc6107,frc9410,frc5045,frc34,frc4020,129.0,37.0
3,1.741965e+09,qm,2025alhu,2025alhu_qm10,10,1.741965e+09,1.741965e+09,1,1.741965e+09,"[{'key': 'xrkAU-qZY-E', 'type': 'youtube'}]",...,1.0,0.0,frc3138,frc3843,frc4020,frc538,frc2338,frc2973,112.0,97.0
4,1.741965e+09,qm,2025alhu,2025alhu_qm11,11,1.741965e+09,1.741965e+09,1,1.741965e+09,"[{'key': 'ae-lJ4geVPg', 'type': 'youtube'}]",...,1.0,1.0,frc7428,frc8772,frc4028,frc6107,frc6517,frc48,61.0,124.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19619,1.752379e+09,sf,2025xxmel,2025xxmel_sf5m1,1,1.752379e+09,1.752379e+09,5,1.752378e+09,[],...,11.0,0.0,frc9146,frc9147,frc9995,frc7128,frc9189,frc5648,85.0,64.0
19620,1.752379e+09,sf,2025xxmel,2025xxmel_sf6m1,1,1.752379e+09,1.752379e+09,6,1.752379e+09,[],...,5.0,0.0,frc4729,frc9986,frc9991,frc9996,frc5876,frc10552,26.0,72.0
19621,1.752380e+09,sf,2025xxmel,2025xxmel_sf7m1,1,1.752380e+09,1.752380e+09,7,1.752380e+09,[],...,0.0,0.0,frc4774,frc4537,frc9994,frc6510,frc5584,frc9974,135.0,65.0
19622,1.752380e+09,sf,2025xxmel,2025xxmel_sf8m1,1,1.752380e+09,1.752380e+09,8,1.752381e+09,[],...,4.0,0.0,frc6996,frc9976,frc9993,frc6497,frc9992,frc10002,90.0,73.0
19623,1.752381e+09,sf,2025xxmel,2025xxmel_sf9m1,1,1.752381e+09,1.752381e+09,9,1.752381e+09,[],...,0.0,0.0,frc4729,frc9986,frc9991,frc4774,frc4537,frc9994,76.0,57.0

In [18]:
red_columns = [col for col in df.columns if 'red' in col]
blue_columns = [col for col in df.columns if 'blue' in col]

In [19]:
df_blue = df.drop([col for col in df.columns if 'red' in col], axis = 1)

In [20]:
df_red = df.drop([col for col in df.columns if 'blue' in col], axis = 1)

In [21]:
df_red

,actual_time,comp_level,event_key,key,match_number,post_result_time,predicted_time,set_number,time,videos,...,red_teleopReef_topRow_nodeI,red_teleopReef_topRow_nodeJ,red_teleopReef_topRow_nodeK,red_teleopReef_topRow_nodeL,red_teleopReef_trough,red_wallAlgaeCount,red_Robot1,red_Robot2,red_Robot3,red_scorePenaltyFree
0,1.742056e+09,f,2025alhu,2025alhu_f1m1,1,1.742056e+09,1.742056e+09,1,1.742056e+09,"[{'key': 'NSWVoO4ZDEs', 'type': 'youtube'}]",...,True,False,False,True,0.0,0.0,frc2783,frc4028,frc7111,124.0
1,1.742058e+09,f,2025alhu,2025alhu_f1m2,2,1.742058e+09,1.742058e+09,1,1.742057e+09,"[{'key': '1FpcfKgS3kw', 'type': 'youtube'}]",...,True,True,True,False,0.0,0.0,frc2783,frc4028,frc7111,144.0
2,1.741960e+09,qm,2025alhu,2025alhu_qm1,1,1.741960e+09,1.741960e+09,1,1.741960e+09,"[{'key': 'mAbsfvQlhaw', 'type': 'youtube'}]",...,False,False,False,False,5.0,2.0,frc5045,frc34,frc4020,129.0
3,1.741965e+09,qm,2025alhu,2025alhu_qm10,10,1.741965e+09,1.741965e+09,1,1.741965e+09,"[{'key': 'xrkAU-qZY-E', 'type': 'youtube'}]",...,True,True,True,True,1.0,0.0,frc538,frc2338,frc2973,112.0
4,1.741965e+09,qm,2025alhu,2025alhu_qm11,11,1.741965e+09,1.741965e+09,1,1.741965e+09,"[{'key': 'ae-lJ4geVPg', 'type': 'youtube'}]",...,False,True,True,True,1.0,1.0,frc6107,frc6517,frc48,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19619,1.752379e+09,sf,2025xxmel,2025xxmel_sf5m1,1,1.752379e+09,1.752379e+09,5,1.752378e+09,[],...,False,True,True,True,11.0,0.0,frc7128,frc9189,frc5648,85.0
19620,1.752379e+09,sf,2025xxmel,2025xxmel_sf6m1,1,1.752379e+09,1.752379e+09,6,1.752379e+09,[],...,False,False,False,False,5.0,0.0,frc9996,frc5876,frc10552,26.0
19621,1.752380e+09,sf,2025xxmel,2025xxmel_sf7m1,1,1.752380e+09,1.752380e+09,7,1.752380e+09,[],...,True,True,True,True,0.0,0.0,frc6510,frc5584,frc9974,135.0
19622,1.752380e+09,sf,2025xxmel,2025xxmel_sf8m1,1,1.752380e+09,1.752380e+09,8,1.752381e+09,[],...,True,True,True,True,4.0,0.0,frc6497,frc9992,frc10002,90.0
19623,1.752381e+09,sf,2025xxmel,2025xxmel_sf9m1,1,1.752381e+09,1.752381e+09,9,1.752381e+09,[],...,False,False,False,False,0.0,0.0,frc4774,frc4537,frc9994,76.0

In [22]:
df_blue

,actual_time,comp_level,event_key,key,match_number,post_result_time,set_number,time,videos,winning_alliance,...,blue_teleopReef_topRow_nodeI,blue_teleopReef_topRow_nodeJ,blue_teleopReef_topRow_nodeK,blue_teleopReef_topRow_nodeL,blue_teleopReef_trough,blue_wallAlgaeCount,blue_Robot1,blue_Robot2,blue_Robot3,blue_scorePenaltyFree
0,1.742056e+09,f,2025alhu,2025alhu_f1m1,1,1.742056e+09,1,1.742056e+09,"[{'key': 'NSWVoO4ZDEs', 'type': 'youtube'}]",blue,...,False,True,True,True,0.0,2.0,frc2338,frc4020,frc10011,143.0
1,1.742058e+09,f,2025alhu,2025alhu_f1m2,2,1.742058e+09,1,1.742057e+09,"[{'key': '1FpcfKgS3kw', 'type': 'youtube'}]",blue,...,True,True,True,True,2.0,3.0,frc2338,frc4020,frc10011,149.0
2,1.741960e+09,qm,2025alhu,2025alhu_qm1,1,1.741960e+09,1,1.741960e+09,"[{'key': 'mAbsfvQlhaw', 'type': 'youtube'}]",red,...,False,False,False,False,0.0,4.0,frc2973,frc6107,frc9410,37.0
3,1.741965e+09,qm,2025alhu,2025alhu_qm10,10,1.741965e+09,1,1.741965e+09,"[{'key': 'xrkAU-qZY-E', 'type': 'youtube'}]",red,...,False,False,False,False,5.0,2.0,frc3138,frc3843,frc4020,97.0
4,1.741965e+09,qm,2025alhu,2025alhu_qm11,11,1.741965e+09,1,1.741965e+09,"[{'key': 'ae-lJ4geVPg', 'type': 'youtube'}]",blue,...,True,False,True,True,0.0,2.0,frc7428,frc8772,frc4028,124.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19619,1.752379e+09,sf,2025xxmel,2025xxmel_sf5m1,1,1.752379e+09,5,1.752378e+09,[],red,...,False,False,False,False,6.0,0.0,frc9146,frc9147,frc9995,64.0
19620,1.752379e+09,sf,2025xxmel,2025xxmel_sf6m1,1,1.752379e+09,6,1.752379e+09,[],blue,...,False,False,False,False,1.0,0.0,frc4729,frc9986,frc9991,72.0
19621,1.752380e+09,sf,2025xxmel,2025xxmel_sf7m1,1,1.752380e+09,7,1.752380e+09,[],red,...,False,False,False,False,0.0,0.0,frc4774,frc4537,frc9994,65.0
19622,1.752380e+09,sf,2025xxmel,2025xxmel_sf8m1,1,1.752380e+09,8,1.752381e+09,[],red,...,False,True,True,True,14.0,0.0,frc6996,frc9976,frc9993,73.0
19623,1.752381e+09,sf,2025xxmel,2025xxmel_sf9m1,1,1.752381e+09,9,1.752381e+09,[],red,...,False,False,False,False,1.0,0.0,frc4729,frc9986,frc9991,57.0

In [23]:
missing = [col for col in red_columns if col.replace('red', 'blue') not in blue_columns]
print(missing)

['predicted_time']

In [24]:
df_red.drop(['predicted_time'], axis = 1, inplace = True)

In [25]:
df_redRobot1 = df_red.drop([col for col in df_red.columns if ('Robot2' in col) or ('Robot3' in col)], axis = 1)
df_redRobot1['possition'] = 1
df_redRobot2 = df_red.drop([col for col in df_red.columns if ('Robot3' in col) or ('Robot1' in col)], axis = 1)
df_redRobot2['possition'] = 2
df_redRobot3 = df_red.drop([col for col in df_red.columns if ('Robot2' in col) or ('Robot1' in col)], axis = 1)
df_redRobot3['possition'] = 3

In [26]:
df_blueRobot1 = df_blue.drop([col for col in df_blue.columns if ('Robot2' in col) or ('Robot3' in col)], axis = 1)
df_blueRobot1['possition'] = 1
df_blueRobot2 = df_blue.drop([col for col in df_blue.columns if ('Robot3' in col) or ('Robot1' in col)], axis = 1)
df_blueRobot2['possition'] = 2
df_blueRobot3 = df_blue.drop([col for col in df_blue.columns if ('Robot2' in col) or ('Robot1' in col)], axis = 1)
df_blueRobot3['possition'] = 3

In [27]:
df_redRobot2

,actual_time,comp_level,event_key,key,match_number,post_result_time,set_number,time,videos,winning_alliance,...,red_teleopReef_topRow_nodeH,red_teleopReef_topRow_nodeI,red_teleopReef_topRow_nodeJ,red_teleopReef_topRow_nodeK,red_teleopReef_topRow_nodeL,red_teleopReef_trough,red_wallAlgaeCount,red_Robot2,red_scorePenaltyFree,possition
0,1.742056e+09,f,2025alhu,2025alhu_f1m1,1,1.742056e+09,1,1.742056e+09,"[{'key': 'NSWVoO4ZDEs', 'type': 'youtube'}]",blue,...,True,True,False,False,True,0.0,0.0,frc4028,124.0,2
1,1.742058e+09,f,2025alhu,2025alhu_f1m2,2,1.742058e+09,1,1.742057e+09,"[{'key': '1FpcfKgS3kw', 'type': 'youtube'}]",blue,...,True,True,True,True,False,0.0,0.0,frc4028,144.0,2
2,1.741960e+09,qm,2025alhu,2025alhu_qm1,1,1.741960e+09,1,1.741960e+09,"[{'key': 'mAbsfvQlhaw', 'type': 'youtube'}]",red,...,False,False,False,False,False,5.0,2.0,frc34,129.0,2
3,1.741965e+09,qm,2025alhu,2025alhu_qm10,10,1.741965e+09,1,1.741965e+09,"[{'key': 'xrkAU-qZY-E', 'type': 'youtube'}]",red,...,True,True,True,True,True,1.0,0.0,frc2338,112.0,2
4,1.741965e+09,qm,2025alhu,2025alhu_qm11,11,1.741965e+09,1,1.741965e+09,"[{'key': 'ae-lJ4geVPg', 'type': 'youtube'}]",blue,...,False,False,True,True,True,1.0,1.0,frc6517,61.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19619,1.752379e+09,sf,2025xxmel,2025xxmel_sf5m1,1,1.752379e+09,5,1.752378e+09,[],red,...,False,False,True,True,True,11.0,0.0,frc9189,85.0,2
19620,1.752379e+09,sf,2025xxmel,2025xxmel_sf6m1,1,1.752379e+09,6,1.752379e+09,[],blue,...,False,False,False,False,False,5.0,0.0,frc5876,26.0,2
19621,1.752380e+09,sf,2025xxmel,2025xxmel_sf7m1,1,1.752380e+09,7,1.752380e+09,[],red,...,True,True,True,True,True,0.0,0.0,frc5584,135.0,2
19622,1.752380e+09,sf,2025xxmel,2025xxmel_sf8m1,1,1.752380e+09,8,1.752381e+09,[],red,...,True,True,True,True,True,4.0,0.0,frc9992,90.0,2
19623,1.752381e+09,sf,2025xxmel,2025xxmel_sf9m1,1,1.752381e+09,9,1.752381e+09,[],red,...,False,False,False,False,False,0.0,0.0,frc4537,76.0,2

In [28]:
df_blueRobot1

,actual_time,comp_level,event_key,key,match_number,post_result_time,set_number,time,videos,winning_alliance,...,blue_teleopReef_topRow_nodeH,blue_teleopReef_topRow_nodeI,blue_teleopReef_topRow_nodeJ,blue_teleopReef_topRow_nodeK,blue_teleopReef_topRow_nodeL,blue_teleopReef_trough,blue_wallAlgaeCount,blue_Robot1,blue_scorePenaltyFree,possition
0,1.742056e+09,f,2025alhu,2025alhu_f1m1,1,1.742056e+09,1,1.742056e+09,"[{'key': 'NSWVoO4ZDEs', 'type': 'youtube'}]",blue,...,True,False,True,True,True,0.0,2.0,frc2338,143.0,1
1,1.742058e+09,f,2025alhu,2025alhu_f1m2,2,1.742058e+09,1,1.742057e+09,"[{'key': '1FpcfKgS3kw', 'type': 'youtube'}]",blue,...,True,True,True,True,True,2.0,3.0,frc2338,149.0,1
2,1.741960e+09,qm,2025alhu,2025alhu_qm1,1,1.741960e+09,1,1.741960e+09,"[{'key': 'mAbsfvQlhaw', 'type': 'youtube'}]",red,...,False,False,False,False,False,0.0,4.0,frc2973,37.0,1
3,1.741965e+09,qm,2025alhu,2025alhu_qm10,10,1.741965e+09,1,1.741965e+09,"[{'key': 'xrkAU-qZY-E', 'type': 'youtube'}]",red,...,False,False,False,False,False,5.0,2.0,frc3138,97.0,1
4,1.741965e+09,qm,2025alhu,2025alhu_qm11,11,1.741965e+09,1,1.741965e+09,"[{'key': 'ae-lJ4geVPg', 'type': 'youtube'}]",blue,...,False,True,False,True,True,0.0,2.0,frc7428,124.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19619,1.752379e+09,sf,2025xxmel,2025xxmel_sf5m1,1,1.752379e+09,5,1.752378e+09,[],red,...,False,False,False,False,False,6.0,0.0,frc9146,64.0,1
19620,1.752379e+09,sf,2025xxmel,2025xxmel_sf6m1,1,1.752379e+09,6,1.752379e+09,[],blue,...,False,False,False,False,False,1.0,0.0,frc4729,72.0,1
19621,1.752380e+09,sf,2025xxmel,2025xxmel_sf7m1,1,1.752380e+09,7,1.752380e+09,[],red,...,False,False,False,False,False,0.0,0.0,frc4774,65.0,1
19622,1.752380e+09,sf,2025xxmel,2025xxmel_sf8m1,1,1.752380e+09,8,1.752381e+09,[],red,...,False,False,True,True,True,14.0,0.0,frc6996,73.0,1
19623,1.752381e+09,sf,2025xxmel,2025xxmel_sf9m1,1,1.752381e+09,9,1.752381e+09,[],red,...,False,False,False,False,False,1.0,0.0,frc4729,57.0,1

In [29]:
df_redRobot1.rename(columns=lambda x: x.replace('Robot1', '').lstrip('_'), inplace = True)
df_redRobot2.rename(columns=lambda x: x.replace('Robot2', '').lstrip('_'), inplace = True)
df_redRobot3.rename(columns=lambda x: x.replace('Robot3', '').lstrip('_'), inplace = True)

In [30]:
df_full_red = pd.concat([df_redRobot1, df_redRobot2, df_redRobot3])

In [31]:
df_full_red.rename(columns={'red_': 'team_number'}, inplace = True)

In [32]:
df_full_red

,actual_time,comp_level,event_key,key,match_number,post_result_time,set_number,time,videos,winning_alliance,...,red_teleopReef_topRow_nodeH,red_teleopReef_topRow_nodeI,red_teleopReef_topRow_nodeJ,red_teleopReef_topRow_nodeK,red_teleopReef_topRow_nodeL,red_teleopReef_trough,red_wallAlgaeCount,team_number,red_scorePenaltyFree,possition
0,1.742056e+09,f,2025alhu,2025alhu_f1m1,1,1.742056e+09,1,1.742056e+09,"[{'key': 'NSWVoO4ZDEs', 'type': 'youtube'}]",blue,...,True,True,False,False,True,0.0,0.0,frc2783,124.0,1
1,1.742058e+09,f,2025alhu,2025alhu_f1m2,2,1.742058e+09,1,1.742057e+09,"[{'key': '1FpcfKgS3kw', 'type': 'youtube'}]",blue,...,True,True,True,True,False,0.0,0.0,frc2783,144.0,1
2,1.741960e+09,qm,2025alhu,2025alhu_qm1,1,1.741960e+09,1,1.741960e+09,"[{'key': 'mAbsfvQlhaw', 'type': 'youtube'}]",red,...,False,False,False,False,False,5.0,2.0,frc5045,129.0,1
3,1.741965e+09,qm,2025alhu,2025alhu_qm10,10,1.741965e+09,1,1.741965e+09,"[{'key': 'xrkAU-qZY-E', 'type': 'youtube'}]",red,...,True,True,True,True,True,1.0,0.0,frc538,112.0,1
4,1.741965e+09,qm,2025alhu,2025alhu_qm11,11,1.741965e+09,1,1.741965e+09,"[{'key': 'ae-lJ4geVPg', 'type': 'youtube'}]",blue,...,False,False,True,True,True,1.0,1.0,frc6107,61.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19619,1.752379e+09,sf,2025xxmel,2025xxmel_sf5m1,1,1.752379e+09,5,1.752378e+09,[],red,...,False,False,True,True,True,11.0,0.0,frc5648,85.0,3
19620,1.752379e+09,sf,2025xxmel,2025xxmel_sf6m1,1,1.752379e+09,6,1.752379e+09,[],blue,...,False,False,False,False,False,5.0,0.0,frc10552,26.0,3
19621,1.752380e+09,sf,2025xxmel,2025xxmel_sf7m1,1,1.752380e+09,7,1.752380e+09,[],red,...,True,True,True,True,True,0.0,0.0,frc9974,135.0,3
19622,1.752380e+09,sf,2025xxmel,2025xxmel_sf8m1,1,1.752380e+09,8,1.752381e+09,[],red,...,True,True,True,True,True,4.0,0.0,frc10002,90.0,3
19623,1.752381e+09,sf,2025xxmel,2025xxmel_sf9m1,1,1.752381e+09,9,1.752381e+09,[],red,...,False,False,False,False,False,0.0,0.0,frc9994,76.0,3

In [33]:
df_blueRobot1.rename(columns=lambda x: x.replace('Robot1', '').lstrip('_'), inplace = True)
df_blueRobot2.rename(columns=lambda x: x.replace('Robot2', '').lstrip('_'), inplace = True)
df_blueRobot3.rename(columns=lambda x: x.replace('Robot3', '').lstrip('_'), inplace = True)

In [34]:
df_full_blue = pd.concat([df_blueRobot1, df_blueRobot2, df_blueRobot3])

In [35]:
df_full_blue.rename(columns={'blue_': 'team_number'}, inplace = True)

In [36]:
df_full_blue

,actual_time,comp_level,event_key,key,match_number,post_result_time,set_number,time,videos,winning_alliance,...,blue_teleopReef_topRow_nodeH,blue_teleopReef_topRow_nodeI,blue_teleopReef_topRow_nodeJ,blue_teleopReef_topRow_nodeK,blue_teleopReef_topRow_nodeL,blue_teleopReef_trough,blue_wallAlgaeCount,team_number,blue_scorePenaltyFree,possition
0,1.742056e+09,f,2025alhu,2025alhu_f1m1,1,1.742056e+09,1,1.742056e+09,"[{'key': 'NSWVoO4ZDEs', 'type': 'youtube'}]",blue,...,True,False,True,True,True,0.0,2.0,frc2338,143.0,1
1,1.742058e+09,f,2025alhu,2025alhu_f1m2,2,1.742058e+09,1,1.742057e+09,"[{'key': '1FpcfKgS3kw', 'type': 'youtube'}]",blue,...,True,True,True,True,True,2.0,3.0,frc2338,149.0,1
2,1.741960e+09,qm,2025alhu,2025alhu_qm1,1,1.741960e+09,1,1.741960e+09,"[{'key': 'mAbsfvQlhaw', 'type': 'youtube'}]",red,...,False,False,False,False,False,0.0,4.0,frc2973,37.0,1
3,1.741965e+09,qm,2025alhu,2025alhu_qm10,10,1.741965e+09,1,1.741965e+09,"[{'key': 'xrkAU-qZY-E', 'type': 'youtube'}]",red,...,False,False,False,False,False,5.0,2.0,frc3138,97.0,1
4,1.741965e+09,qm,2025alhu,2025alhu_qm11,11,1.741965e+09,1,1.741965e+09,"[{'key': 'ae-lJ4geVPg', 'type': 'youtube'}]",blue,...,False,True,False,True,True,0.0,2.0,frc7428,124.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19619,1.752379e+09,sf,2025xxmel,2025xxmel_sf5m1,1,1.752379e+09,5,1.752378e+09,[],red,...,False,False,False,False,False,6.0,0.0,frc9995,64.0,3
19620,1.752379e+09,sf,2025xxmel,2025xxmel_sf6m1,1,1.752379e+09,6,1.752379e+09,[],blue,...,False,False,False,False,False,1.0,0.0,frc9991,72.0,3
19621,1.752380e+09,sf,2025xxmel,2025xxmel_sf7m1,1,1.752380e+09,7,1.752380e+09,[],red,...,False,False,False,False,False,0.0,0.0,frc9994,65.0,3
19622,1.752380e+09,sf,2025xxmel,2025xxmel_sf8m1,1,1.752380e+09,8,1.752381e+09,[],red,...,False,False,True,True,True,14.0,0.0,frc9993,73.0,3
19623,1.752381e+09,sf,2025xxmel,2025xxmel_sf9m1,1,1.752381e+09,9,1.752381e+09,[],red,...,False,False,False,False,False,1.0,0.0,frc9991,57.0,3

In [37]:
df_full_red.rename(columns=lambda x: x.replace('red', '').lstrip('_'), inplace=True)
df_full_blue.rename(columns=lambda x: x.replace('blue', '').lstrip('_'), inplace=True)

In [38]:
df_full_red['alliance'] = 'red'
df_full_blue['alliance'] = 'blue'

In [39]:
full_df2 = pd.concat([df_full_red, df_full_blue])

In [40]:
full_df2

,actual_time,comp_level,event_key,key,match_number,post_result_time,set_number,time,videos,winning_alliance,...,teleopReef_topRow_nodeI,teleopReef_topRow_nodeJ,teleopReef_topRow_nodeK,teleopReef_topRow_nodeL,teleopReef_trough,wallAlgaeCount,team_number,scorePenaltyFree,possition,alliance
0,1.742056e+09,f,2025alhu,2025alhu_f1m1,1,1.742056e+09,1,1.742056e+09,"[{'key': 'NSWVoO4ZDEs', 'type': 'youtube'}]",blue,...,True,False,False,True,0.0,0.0,frc2783,124.0,1,red
1,1.742058e+09,f,2025alhu,2025alhu_f1m2,2,1.742058e+09,1,1.742057e+09,"[{'key': '1FpcfKgS3kw', 'type': 'youtube'}]",blue,...,True,True,True,False,0.0,0.0,frc2783,144.0,1,red
2,1.741960e+09,qm,2025alhu,2025alhu_qm1,1,1.741960e+09,1,1.741960e+09,"[{'key': 'mAbsfvQlhaw', 'type': 'youtube'}]",red,...,False,False,False,False,5.0,2.0,frc5045,129.0,1,red
3,1.741965e+09,qm,2025alhu,2025alhu_qm10,10,1.741965e+09,1,1.741965e+09,"[{'key': 'xrkAU-qZY-E', 'type': 'youtube'}]",red,...,True,True,True,True,1.0,0.0,frc538,112.0,1,red
4,1.741965e+09,qm,2025alhu,2025alhu_qm11,11,1.741965e+09,1,1.741965e+09,"[{'key': 'ae-lJ4geVPg', 'type': 'youtube'}]",blue,...,False,True,True,True,1.0,1.0,frc6107,61.0,1,red
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19619,1.752379e+09,sf,2025xxmel,2025xxmel_sf5m1,1,1.752379e+09,5,1.752378e+09,[],red,...,False,False,False,False,6.0,0.0,frc9995,64.0,3,blue
19620,1.752379e+09,sf,2025xxmel,2025xxmel_sf6m1,1,1.752379e+09,6,1.752379e+09,[],blue,...,False,False,False,False,1.0,0.0,frc9991,72.0,3,blue
19621,1.752380e+09,sf,2025xxmel,2025xxmel_sf7m1,1,1.752380e+09,7,1.752380e+09,[],red,...,False,False,False,False,0.0,0.0,frc9994,65.0,3,blue
19622,1.752380e+09,sf,2025xxmel,2025xxmel_sf8m1,1,1.752380e+09,8,1.752381e+09,[],red,...,False,True,True,True,14.0,0.0,frc9993,73.0,3,blue
19623,1.752381e+09,sf,2025xxmel,2025xxmel_sf9m1,1,1.752381e+09,9,1.752381e+09,[],red,...,False,False,False,False,1.0,0.0,frc9991,57.0,3,blue

In [41]:
full_df2.dropna(inplace = True)

In [42]:
full_df2.to_csv('full_table2.csv', index=False)